services:
  api:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    container_name: constance-api
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////data/robes_demi_mesure.db

      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}

      - SEED_SAMPLE_DATA=0
    volumes:
      - constance_db:/data
    ports:
      - "8000:8000"
    depends_on:
      - smtp

  front:
    build:
      context: ./boutique-front
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:8000"
    container_name: constance-front
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api

  smtp:
    image: rnwood/smtp4dev:v3
    container_name: constance-smtp
    ports:
      - "5000:80"   # UI web
      - "2525:25"   # SMTP

volumes:
  constance_db:
